plugins {
    id 'com.android.library'
    id 'com.chaquo.python'
}

android {
    compileSdk 33

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        python {
            buildPython("C:/Users/PPP/AppData/Local/Programs/Python/Python38/python.exe")
            pip {
                install "lxml"
                install "ujson"
                install "pyquery==2.0.2"
                install "requests"
                install "jsonpath"
                install "cachetools"
                install 'pycryptodome'
                install 'beautifulsoup4'
            }
        }
    }

    flavorDimensions "mode"
    productFlavors {
        python {
            dimension "mode"
            ndk {
                abiFilters "armeabi-v7a", "arm64-v8a"
            }
        }
        python32 {
            dimension "mode"
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
        python64 {
            dimension "mode"
            ndk {
                abiFilters "arm64-v8a"
            }
        }
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main{
            // Android代码模块
            setRoot "src/main"
            // Python代码模块，也就是你的Python源码所在项目中的文件夹
            python.srcDirs = ["src/python"]
        }
    }
    buildToolsVersion '30.0.3'
}

dependencies {

}
